### ISSUE TITLE
'Enter' doesn't fire 'submit'

### ISSUE THREAD

**Issue by MissArray** [fac-14/JEES-LOUISE#42]
We had the same issue in last week's project. I haven't tried correcting that issue, but suspect the following approach might get you somewhere, as you are using a form:

`*There are a js-free solution.

Set type=submit to the button you'd like to be default and type=button to other buttons. Now in the form below you can hit Enter in any input fields, and the Render button will work (despite the fact it is the second button in the form).

Example:*

    <button id='close_renderer_button' class='btn btn-success'
            title='Перейти к редактированию программы'
            type=button>
      <span class='glyphicon glyphicon-edit'> </span> Edit program
    </button>
    <button id='render_button' class='btn btn-primary'
            title='Построить фрактал'
            type=submit
            formaction='javascript:alert("Bingo!");'>
      <span class='glyphicon glyphicon-send'> </span> Render
    </button>

*Tested in FF24 and Chrome 35 (formaction is html5 feature, but type is not).*`

https://stackoverflow.com/questions/12955222/how-to-trigger-html-button-when-you-press-enter-in-textbox

**Comment by VirtualDOMinic** [comment]
Enter for submitting works for me
